# Generated by Django 4.2.3 on 2023-07-18 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=250)),
                ('agent_address', models.CharField(max_length=200)),
                ('agent_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Land',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('land_title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('county', models.CharField(max_length=50)),
                ('land_size', models.PositiveIntegerField(default=0)),
                ('land_category', models.CharField(choices=[('Residential', 'Residential'), ('Agricultural', 'Agricultural'), ('Commercial', 'Commercial'), ('Industrial', 'Industrial'), ('Raw Land', 'Raw Land')], max_length=50)),
                ('price', models.PositiveIntegerField()),
                ('date_created', models.DateField(auto_now_add=True)),
                ('description', models.TextField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_title', models.CharField(max_length=250)),
                ('house_image', models.ImageField(default='', upload_to='')),
                ('location', models.CharField(max_length=250)),
                ('num_of_rooms', models.PositiveIntegerField()),
                ('sqr_feet', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('pricing', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('RENTAL', 'Rental'), ('FOR SALE', 'For Sale')], max_length=200)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('client_id', models.CharField(max_length=100)),
                ('client_address', models.CharField(max_length=200)),
                ('contact_person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='houses.agent')),
            ],
        ),
    ]
