# Generated by Django 4.2.3 on 2023-07-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houses',
            old_name='num_of_rooms',
            new_name='bathrooms',
        ),
        migrations.AddField(
            model_name='houses',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
