# Generated by Django 4.2.3 on 2023-07-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_alter_houses_house_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='land_image',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
