# Generated by Django 4.2.3 on 2023-07-19 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0004_land_land_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='land_image',
            field=models.ImageField(upload_to=''),
        ),
    ]
