# Generated by Django 4.2.3 on 2023-07-19 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_alter_land_land_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='houses',
            old_name='pricing',
            new_name='pricing_in_dollars',
        ),
    ]
