# Generated by Django 4.2.3 on 2023-07-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_rename_pricing_houses_pricing_in_dollars'),
    ]

    operations = [
        migrations.AddField(
            model_name='houses',
            name='houseImage1',
            field=models.ImageField(default='image.jpg', upload_to='houses/media'),
        ),
        migrations.AddField(
            model_name='houses',
            name='houseImage2',
            field=models.ImageField(default='image.jpg', upload_to='houses/media'),
        ),
        migrations.AddField(
            model_name='houses',
            name='houseImage3',
            field=models.ImageField(default='image.jpg', upload_to='houses/media'),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_image',
            field=models.ImageField(upload_to='houses/media'),
        ),
    ]
