# Generated by Django 4.2.3 on 2023-07-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0008_alter_houses_houseimage1_alter_houses_houseimage2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='houseImage1',
            field=models.ImageField(default='mansion1.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='houseImage2',
            field=models.ImageField(default='mansion1.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='houseImage3',
            field=models.ImageField(default='mansion1.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_image',
            field=models.ImageField(default='mansion1.jpg', upload_to=''),
        ),
    ]
