# Generated by Django 4.2.3 on 2023-07-20 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0009_alter_houses_houseimage1_alter_houses_houseimage2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='land',
            name='landImage1',
            field=models.ImageField(default='mansion1.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='land',
            name='landImage2',
            field=models.ImageField(default='mansion1.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='land',
            name='landImage3',
            field=models.ImageField(default='mansion1.jpg', upload_to=''),
        ),
    ]
