# Generated by Django 4.2.3 on 2023-07-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_land_landimage1_land_landimage2_land_landimage3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='houses',
            name='houseImage1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='houseImage2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='houseImage3',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='houses',
            name='house_image',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='land',
            name='landImage1',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='land',
            name='landImage2',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='land',
            name='landImage3',
            field=models.ImageField(upload_to=''),
        ),
    ]
