# Generated by Django 4.2.3 on 2023-08-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0011_alter_houses_houseimage1_alter_houses_houseimage2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_person',
        ),
        migrations.AddField(
            model_name='client',
            name='email_address',
            field=models.EmailField(default='mutiaronald138@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='0790021016', max_length=20),
            preserve_default=False,
        ),
    ]
