# Generated by Django 4.2.3 on 2023-08-13 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0012_remove_client_contact_person_client_email_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
